name: Streamlit SMHI Weather App

on:
  push:
    branches: [ "FK3" ]

  workflow_dispatch:
    inputs:
      logging_errors:
        description: Create artifact log if a test fails
        required: true
        default: true
        type: choice
        options:
          - true
          - false


env:
  IMAGE_NAME: fkron95/streamlit-smhi-weather-app
  APP_NAME: SMHI-Web-App
  PYTHON_VERSION: 3.11


jobs:

  environment_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt


  tests:
    name: Run a pytest on API retrieval and data processing
    runs-on: ubuntu-latest
    needs: environment_check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest test_api.py test_process_smhi_data.py test_if_failure.py --doctest-modules --junitxml=junit/test-results-${{ env.PYTHON_VERSION }}.xml || echo "TESTS_FAILED=true" >> $GITHUB_ENV

      - name: Upload pytest test results
        if: ${{ env.TESTS_FAILED == 'true' && github.event.inputs.logging_errors == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: pytest-test-results
          path: junit/test-results-${{ env.PYTHON_VERSION }}.xml
      
      - name: Failure of job if tests failed
        if: ${{ env.TESTS_FAILED == 'true' }}
        run: |
          echo "One or more tests have failed."
          exit 1
          
  deployment:
    name: Build and Push Docker Image to Docker Hub and Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: tests
    if: needs.tests.result == 'success'

    steps:
      - name : Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest